### ISSUE TITLE
Kortet presenterar sig inte med preview

### ISSUE THREAD

**Issue by Jottlas** [TekniskSupport/home-assistant-pollen-card#3]
Tack för vad som verkar vara ett jättebra kort. Jag får det dock inte att fungera.
Till och börja med presenterar sig kortet inte med en preview i då jag gör "+ Add card"  i en lovelace dashboard. Borde det göra det om jag gjort installationen rätt?
Vidare blir jag inte klok på var jag ska klistra in koden (eller min mod. av den) som anges i "Example configuration"?

Är ny på Github och vet inte om detta är rätt ställe och sätt att be om hjälp med detta.

**Comment by labaland** [comment]
> Tack för vad som verkar vara ett jättebra kort. Jag får det dock inte att fungera.
> Till och börja med presenterar sig kortet inte med en preview i då jag gör "+ Add card" i en lovelace dashboard. Borde det göra det om jag gjort installationen rätt?
> Vidare blir jag inte klok på var jag ska klistra in koden (eller min mod. av den) som anges i "Example configuration"?
> 
> Är ny på Github och vet inte om detta är rätt ställe och sätt att be om hjälp med detta.

Jag får det inte att fungera heller 😆🤔😟

**Comment by TekniskSupport** [comment]
Det här kortet tillverkades för ett par år sedan ursprungligen,  innan det gick att lägga till kort via UI-editorn, ni får nog lägga till det i yaml-mode skulle jag tro

Men det skall gå att växla till yamlläge även i ui-editorn på något sätt, aldrig använt det själv så är inte helt säker på hur

**Comment by labaland** [comment]
> Det här kortet tillverkades för ett par år sedan ursprungligen, innan det gick att lägga till kort via UI-editorn, ni får nog lägga till det i yaml-mode skulle jag tro
> 
> Men det skall gå att växla till yamlläge även i ui-editorn på något sätt, aldrig använt det själv så är inte helt säker på hur

Gör alltid yaml i ui editorn :P men ja de kan va jag som gör fel men övriga kort funkar jag har atm :P

**Comment by Jottlas** [comment]
Jag går till dashboarden jag vill ha kortet på. Klickar knappen "+Add card". I "dialogen" som kommer upp skrollar jag längst ner och väljer "Manual  - Need to add a custom card or just want to manually write the YAML?".  
Här kan jag skriva kortets yaml, men vet ej exakt vilken kod det ska vara. Den verkar inte känna igen `"type: custom:home-assistant-pollen-card"`
![image](https://user-images.githubusercontent.com/35530660/115252580-e1451a00-a12b-11eb-81ef-2c4daf2e9be9.png)

Tror mig ha gjort installationen helt rätt i HACS (Home Assistant Pollen Card listas bland HACS installerade frontend-komponenter), men uppenbarligen inte.. ?

**Comment by jhqv** [comment]
Jag har exakt samma problem, så ni är inte ensamma om det.
Går jag till manage resources (via ...-knappen längst upp till höger i Lovelace) så ser jag js-filen där, och jag ser den som en "Source" i Chrome:s debugläge, men jag får samma felmeddelande i Lovelace.

**Comment by TekniskSupport** [comment]
Alright sorry, det är fel namn på kortet i guiden; testa detta istället:
      - type: custom:pollenkoll-card
      
      Jag skall se om jag får ut en uppdatering som gör att det fungerar med båda namnen.

**Comment by jhqv** [comment]
> Alright sorry, det är fel namn på kortet i guiden; testa detta istället:
> - type: custom:pollenkoll-card

@TekniskSupport  Bingo, det funkade direkt. Stort tack!
Tyvärr funkar inte bilderna för mig - de laddas från /local/pollen_img/2.svg och blir 404:or allihopa.
(Kan tillägga att jag installerat både pollenintegrationen och pollenkortet som custom repos i HACS.)

**Comment by TekniskSupport** [comment]
bilderna skall ligga i en mapp direkt under www
mappen skall heta pollen_img

**Comment by jhqv** [comment]
> bilderna skall ligga i en mapp direkt under www
> mappen skall heta pollen_img

Uppfattat. Verkar som att HACS bara drog ner JS-filen men inte bildmappen, det förklarar saken.

**Comment by Jottlas** [comment]
Kanon! Med rätt namn på kortet och bildmappen lagd på plats manuellt så funkar det nu! Tack alla!

**Comment by TekniskSupport** [comment]
Nu har jag gjort en uppdatering så att dokumentationen matchar koden
