### ISSUE TITLE
Usage of images

### ISSUE THREAD

**Issue by leahoswald** [TekniskSupport/home-assistant-pollen-card#4]
Hey,
I've build a version of the currently [maintained fork](https://github.com/isabellaalstrom/lovelace-pollenprognos-card) to support the german weather service. Before publishing it I would like to ask if I'm allowed to use the images from your repo because I couldn't find a license? I've also added missing images for rye and ash from public domain sources.
![Screenshot2022-02-13_00-15-37](https://user-images.githubusercontent.com/1292551/153749797-abc9dd2f-9db4-4cf3-b34a-bf3b884fa3e1.png)

**Comment by TekniskSupport** [comment]
Great work, go ahead and use them for your project without restrictions or limitations

**Comment by leahoswald** [comment]
For reference: https://github.com/leahoswald/lovelace-dwd-pollenprognose-card
